### ISSUE TITLE
Implement logout and a database-persisted JWT Blacklist

### ISSUE THREAD

**Issue by viktorKhan** [lucoenergia/conluz#82]
# Task: Logout

Revoke an access token to prevent being used again and mark access token cookie to be removed from the client.

# Task: Implement a Database-Persisted JWT Blacklist

---

## Objective

Prevent revoked JWT tokens (e.g., after logout or for security reasons) from being reused until their natural expiration. To achieve this, implement a **blacklist** persisted in a database and checked on every authenticated request.

---

## 1. Scope

- Create a database structure to store revoked tokens.
- Modify the logout process to insert tokens into the blacklist.
- Implement a filter or component that checks if a token is blacklisted on each request.
- Periodically remove expired tokens from the blacklist.

---

## 2. Functional Requirements

- [x] JWTs must include a unique identifier (`jti`) to track them.
- [x] The backend must store the `jti` of revoked tokens along with their expiration time.
- [x] Every authenticated request must verify whether the token's `jti` is in the blacklist.
- [x] If the token is blacklisted, the request must be rejected with a `401 Unauthorized`.
- [x] On logout, the current token must be added to the blacklist with its expiration date.

---

## 3. Database Model

```sql
CREATE TABLE jwt_blacklist (
    jti VARCHAR(64) PRIMARY KEY,
    expiration TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```
---

### 4.1. Include `jti` in JWT

Ensure all issued JWTs include a `jti` (JWT ID) claim.
Example when generating the token:

```java
String jti = UUID.randomUUID().toString();

String jwt = Jwts.builder()
    .setSubject(username)
    .setId(jti)
    .setIssuedAt(now)
    .setExpiration(expiration)
    .signWith(secretKey)
    .compact();
```

---

### 4.2. Add token to blacklist on logout

```java
public void blacklistToken(String jti, Instant expiration) {
    jwtBlacklistRepository.save(new BlacklistedToken(jti, expiration));
}
```

---

### 4.3. Check blacklist on each request

Create a custom security filter that:

* Runs after the JWT is validated.
* Extracts the `jti` from the token.
* Queries the database: if the `jti` is found in the blacklist, reject the request.

```java
if (blacklistRepository.existsByJti(jti)) {
    throw new JwtAuthenticationException("Token has been revoked");
}
```

---

### 4.4. Clean up expired tokens

Schedule a periodic task (e.g., using `@Scheduled`) to remove entries where `expiration < now()`.

```java
@Scheduled(cron = "0 0 * * * *") // every hour
public void cleanupExpiredTokens() {
    jwtBlacklistRepository.deleteAllExpiredBefore(Instant.now());
}
```

---

## 5. Acceptance Criteria

- [x] On logout, the access token is added to the blacklist.
- [x] Reuse of a revoked token results in authentication failure.
- [x] Expired tokens are automatically removed from the database.
- [x] The blacklist lookup does not significantly impact performance.
- [x] Unit and integration tests cover valid, revoked, and expired token scenarios.

---

## 6. Deliverables

* `BlacklistedToken` entity and JPA repository.
* Custom security filter that checks the blacklist.
* Updated logout logic to blacklist the current token.
* Scheduled cleanup job.
* Unit and integration tests.
* Documentation of the blacklist behavior and expected client-side handling.
